#aws --profile oseven cloudformation create-stack --stack-name oseven-homepage --template-body file://<(cfn-flip awsInfrastruktur.yml)
#aws --profile oseven cloudformation update-stack --stack-name oseven-homepage --template-body file://<(cfn-flip awsInfrastruktur.yml)

AWSTemplateFormatVersion: "2010-09-09"
Description: API Gatway für die Backend-API für Frontendcalls

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      Tags:
        - Key: customer
          Value: oseven
        - Key: app
          Value: homepage

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      Tags:
        - Key: customer
          Value: oseven
        - Key: app
          Value: homepage
      DistributionConfig:
        Aliases:
          - oseven.de
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          TargetOriginId: myS3Origin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: false
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - DomainName: !GetAtt s3Bucket.DomainName
            Id: myS3Origin # WELCHE ID?
            OriginPath: /prod
            S3OriginConfig:
              OriginAccessIdentity:
                !Join [
                  "",
                  [
                    "origin-access-identity/cloudfront/",
                    !Ref OriginAccessIdentity,
                  ],
                ]

        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:403039540759:certificate/38d411c0-7e0b-4476-a3a8-118bc84a4a20
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only

  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: access-identity-oseven.de.s3.amazonaws.com

  # Recordsets:
  #   Type: AWS::Route53::RecordSetGroup
  #   Properties:
  #     Comment: oseven wegPage
  #     HostedZoneId: Z3340Y06FZ5TQI
  #     RecordSets:
  #       - Name: oseven.de
  #         Type: A
  #         TTL: "900"
  #         AliasTarget:
  #           DNSName: !GetAtt CloudFrontDistribution.DomainName
  #           HostedZoneId: Z2FDTNDATAQYW2

  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Location: !Ref s3Bucket
        Path: public
        Type: S3
        Packaging: NONE
        EncryptionDisabled: true
        Name: "/"
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:1.0
        Type: LINUX_CONTAINER
      Name: Homepage-oseven
      ServiceRole: arn:aws:iam::403039540759:role/CodeBuildAdmin
      Source:
        Type: GITHUB
        Location: https://github.com/oseven-development/website_oseven.git
      SourceVersion: awsprod
      QueuedTimeoutInMinutes: 15
      Tags:
        - Key: customer
          Value: oseven
        - Key: app
          Value: homepage
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: ^refs/heads/awsprod$
